/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/335ec642-bb0e-4a2c-a1f4-971a7ffb9da3 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float moisture;
  float temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
 #include "DHT.h" //humidity & temperature
 #define DHTPIN 2 
 #define DHTTYPE DHT11
 #include <Wire.h>           // ADDRESS of lcd 
 #include <LiquidCrystal_I2C.h>    // lcd library
 LiquidCrystal_I2C lcd(0x27,16,2); // 16col x2row
 DHT dht(DHTPIN,DHT11); //data pin #, type of sensor
 const int sensor_pin = A0; 

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);  // baud rate
  lcd.init();      // initialize
  lcd.backlight(); // green light
  dht.begin();

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  delay(2000);
  moisture = ( 101.00 - ( (analogRead(sensor_pin)/1023.00) * 100.00 ) );
   humidity = dht.readHumidity();
   temperature = dht.readTemperature();

  if (isnan(humidity) || isnan(temperature)) {
      Serial.println("Failed to read from DHT sensor!");
      return;
   }  
  
  Serial.print("Soil Moisture %: ");
  Serial.print(moisture);
  Serial.println("%");
   Serial.print("Temperature in Celsius:");  
   Serial.print(temperature); 
   Serial.println(" *C"); 
   Serial.print("Humidity% :");  
   Serial.println(humidity);  
   delay(5000);  
   if(moisture >100 && humidity>40 && humidity<=70 && temperature>0 && temperature<=35)
  {
    lcd.clear();
    lcd.setCursor(0,0);  
    lcd.print("   Plant is ");  
    lcd.setCursor(0,1);  
    lcd.print("  HAPPY :)) ");  
  }    
  else
  {
    lcd.clear();
    lcd.setCursor(0,0);  
    lcd.print("    Plant is  ");  
    lcd.setCursor(0,1);  
    lcd.print("  SAD :(( ");
  } 
  
  
}


/*
  Since Moisture is READ_WRITE variable, onMoistureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMoistureChange()  {
  // Add your code here to act upon Moisture change
}

/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}

/*
  Since Humidity is READ_WRITE variable, onHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange()  {
  // Add your code here to act upon Humidity change
}